source 'https://github.com/CocoaPods/Specs.git'

target 'MBVineVideo', :exclusive => true do
  pod "MBVineVideo", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MBVineVideo", :path => "../"

  
end
